/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.NurseRole;

import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.NurseOrganization;
import business.Patient.Patient;
import business.UserAccount.UserAccount;
import business.WorkQueue.BloodRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maalp
 */
public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseWorkAreaJPanel
     */
    JPanel container;
    NurseOrganization nurseOrganization;
    UserAccount userAccount;
    Enterprise enterprise;
    Network network;
    public NurseWorkAreaJPanel(JPanel container, UserAccount account, NurseOrganization nurseOrganization, Enterprise enterprise, Network network) {
        initComponents();
        this.container = container;
        this.nurseOrganization = nurseOrganization;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.network = network;
        refreshTable();
        populateBloodRequestTable();
        
    }
    
    public void refreshTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblPatient.getModel();
        dtm.setRowCount(0);
        for(Patient patient : nurseOrganization.getPatientDirectory().getPatientList()){
           Object[] row = new Object[3];
           row[0] = patient.getPatientID();
           row[1] = patient;
           row[2] = patient.getDateAdmitted();
            
           dtm.addRow(row);
    }
    }
    
    private void populateBloodRequestTable()
    {
        DefaultTableModel model = (DefaultTableModel)tblBloodRequest.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : nurseOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request.getRequestDate();
            row[1] = request.getPatientName();
            row[2] = request;
            row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[4] = request.getStatus();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        btnRegisterPatient = new javax.swing.JButton();
        btnRecordVitalSigns = new javax.swing.JButton();
        btnDischargePatient = new javax.swing.JButton();
        btnPatientHistory = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnBloodBank = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        nurseContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBloodRequest = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        lblBanner = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        SplitPane.setDividerLocation(250);

        leftPanel.setBackground(new java.awt.Color(0, 153, 204));

        btnRegisterPatient.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRegisterPatient.setText("Register Patient");
        btnRegisterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPatientActionPerformed(evt);
            }
        });

        btnRecordVitalSigns.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRecordVitalSigns.setText("Record Vital Signs");
        btnRecordVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordVitalSignsActionPerformed(evt);
            }
        });

        btnDischargePatient.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnDischargePatient.setText("Discharge Patient");
        btnDischargePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDischargePatientActionPerformed(evt);
            }
        });

        btnPatientHistory.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnPatientHistory.setText("View Patient History");
        btnPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientHistoryActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnBloodBank.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBloodBank.setText("View Blood Reserve");
        btnBloodBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloodBankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPatientHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecordVitalSigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegisterPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDischargePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnBloodBank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(btnRegisterPatient)
                .addGap(18, 18, 18)
                .addComponent(btnRecordVitalSigns)
                .addGap(18, 18, 18)
                .addComponent(btnPatientHistory)
                .addGap(18, 18, 18)
                .addComponent(btnDischargePatient)
                .addGap(18, 18, 18)
                .addComponent(btnBloodBank)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(leftPanel);

        rightPanel.setLayout(new java.awt.CardLayout());

        nurseContainer.setBackground(new java.awt.Color(0, 153, 204));
        nurseContainer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                nurseContainerComponentShown(evt);
            }
        });

        tblPatient.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Date Admitted"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatient.setRowHeight(30);
        jScrollPane1.setViewportView(tblPatient);

        tblBloodRequest.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblBloodRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Date", "Sender", "Blood Type", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBloodRequest.setRowHeight(30);
        jScrollPane2.setViewportView(tblBloodRequest);
        if (tblBloodRequest.getColumnModel().getColumnCount() > 0) {
            tblBloodRequest.getColumnModel().getColumn(0).setResizable(false);
            tblBloodRequest.getColumnModel().getColumn(1).setResizable(false);
            tblBloodRequest.getColumnModel().getColumn(2).setResizable(false);
            tblBloodRequest.getColumnModel().getColumn(3).setResizable(false);
            tblBloodRequest.getColumnModel().getColumn(4).setResizable(false);
        }

        btnAccept.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        lblBanner.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        lblBanner.setText("Nurse Work Area");

        javax.swing.GroupLayout nurseContainerLayout = new javax.swing.GroupLayout(nurseContainer);
        nurseContainer.setLayout(nurseContainerLayout);
        nurseContainerLayout.setHorizontalGroup(
            nurseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nurseContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nurseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nurseContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAccept)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(nurseContainerLayout.createSequentialGroup()
                        .addComponent(lblBanner)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        nurseContainerLayout.setVerticalGroup(
            nurseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nurseContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBanner)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAccept)
                .addGap(191, 191, 191))
        );

        rightPanel.add(nurseContainer, "card2");

        SplitPane.setRightComponent(rightPanel);

        add(SplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPatientActionPerformed
        // TODO add your handling code here:
        RegisterPatient panel = new RegisterPatient(rightPanel, nurseOrganization);
        rightPanel.add("Register New Patient",panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
        btnRegisterPatient.setEnabled(false);
        btnBloodBank.setEnabled(false);
        btnDischargePatient.setEnabled(false);
        btnRecordVitalSigns.setEnabled(false);
        btnPatientHistory.setEnabled(false);
        
    }//GEN-LAST:event_btnRegisterPatientActionPerformed

    private void btnRecordVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordVitalSignsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a Row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            btnRegisterPatient.setEnabled(false);
            btnBloodBank.setEnabled(false);
            btnDischargePatient.setEnabled(false);
            btnRecordVitalSigns.setEnabled(false);
            btnPatientHistory.setEnabled(false);
            Patient patient  =  (Patient) tblPatient.getValueAt(selectedRow,1);
            RecordVitalSigns recordVitalSigns = new RecordVitalSigns(rightPanel, patient);
            rightPanel.add("RecordvitalSigns", recordVitalSigns);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.next(rightPanel);
        }
    }//GEN-LAST:event_btnRecordVitalSignsActionPerformed

    private void btnDischargePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDischargePatientActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow >= 0){
            int dialogResult = JOptionPane.showConfirmDialog(null,"Is the patient's disease treated successfully and want to discharge?","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                Patient patient= (Patient) tblPatient.getValueAt(selectedRow,1);
                DefaultTableModel dtm=(DefaultTableModel) tblPatient.getModel();
                dtm.removeRow(selectedRow);
                refreshTable();
            }
        }
          else
            JOptionPane.showMessageDialog(null, "PLEASE SELECT A ROW","WARNING",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnDischargePatientActionPerformed

    private void btnPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientHistoryActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a Row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
             btnRegisterPatient.setEnabled(false);
             btnBloodBank.setEnabled(false);
             btnDischargePatient.setEnabled(false);
             btnRecordVitalSigns.setEnabled(false);
             btnPatientHistory.setEnabled(false);
             Patient patient  = (Patient) tblPatient.getValueAt(selectedRow,1);
             PatientHistory patientHistory = new PatientHistory(rightPanel, patient);
             rightPanel.add("Patient History", patientHistory);
             CardLayout layout = (CardLayout) rightPanel.getLayout();
             layout.next(rightPanel);
        }
    }//GEN-LAST:event_btnPatientHistoryActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        rightPanel.removeAll();
        rightPanel.add(nurseContainer);
        refreshTable();
        populateBloodRequestTable();
        btnRegisterPatient.setEnabled(true);
        btnBloodBank.setEnabled(true);
        btnDischargePatient.setEnabled(true);
        btnRecordVitalSigns.setEnabled(true);
        btnPatientHistory.setEnabled(true);
       

    }//GEN-LAST:event_btnHomeActionPerformed

    private void nurseContainerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_nurseContainerComponentShown
        refreshTable();
        populateBloodRequestTable();
        btnRegisterPatient.setEnabled(true);
        btnBloodBank.setEnabled(true);
        btnDischargePatient.setEnabled(true);
        btnRecordVitalSigns.setEnabled(true);
        btnPatientHistory.setEnabled(true);
    }//GEN-LAST:event_nurseContainerComponentShown

    private void btnBloodBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloodBankActionPerformed
        // TODO add your handling code here:
        btnRegisterPatient.setEnabled(false);
        btnBloodBank.setEnabled(false);
        btnDischargePatient.setEnabled(false);
        btnRecordVitalSigns.setEnabled(false);
        btnPatientHistory.setEnabled(false);
        ViewBloodBank viewBloodBank = new ViewBloodBank(rightPanel, nurseOrganization, network, userAccount);
            rightPanel.add("Blood Bank", viewBloodBank);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.next(rightPanel);
    }//GEN-LAST:event_btnBloodBankActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBloodRequest.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
        BloodRequest request = (BloodRequest)tblBloodRequest.getValueAt(selectedRow, 2);
        if(request.getStatus().equalsIgnoreCase("Processed"))
        {
        request.setStatus("Completed");
        populateBloodRequestTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Sorry this request is not processed yet!!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBloodBank;
    private javax.swing.JButton btnDischargePatient;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPatientHistory;
    private javax.swing.JButton btnRecordVitalSigns;
    private javax.swing.JButton btnRegisterPatient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel nurseContainer;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTable tblBloodRequest;
    private javax.swing.JTable tblPatient;
    // End of variables declaration//GEN-END:variables
}
