/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        patientNameLabel = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        testsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTests = new javax.swing.JTextArea();
        btnRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 240, 240));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 120, 30));

        patientNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        patientNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        patientNameLabel.setText("Patient Name:");
        add(patientNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        txtPatientName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtPatientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPatientNameKeyTyped(evt);
            }
        });
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 220, -1));

        testsLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        testsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        testsLabel.setText("Tests:");
        add(testsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        areaTests.setColumns(20);
        areaTests.setRows(5);
        jScrollPane1.setViewportView(areaTests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        btnRequest.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientNameKeyTyped
        char ch = evt.getKeyChar();
        if(!(Character.isAlphabetic(ch)) || (ch == KeyEvent.VK_BACK_SPACE) || (ch == KeyEvent.VK_DELETE))
        {
            evt.consume();
            if(Character.isDigit(ch) || Character.isSpaceChar(ch))
            JOptionPane.showMessageDialog(null,"Enter alphabetical values only.");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameKeyTyped
/*
    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        if(txtPatientName.getText().isEmpty() || areaTests.getText().trim().isEmpty())
            JOptionPane.showMessageDialog(null, "Please enter all the values", "WARNING", JOptionPane.WARNING_MESSAGE);
        else if(txtPatientName.getText().matches("[^([A-Za-z])+$]"))
            JOptionPane.showMessageDialog(null, "Please enter name correctly", "WARNING", JOptionPane.WARNING_MESSAGE);
        else if(areaTests.getText().trim().matches("^[A-Z0-9 _]*$"))
            JOptionPane.showMessageDialog(null, "Please enter name correctly", "WARNING", JOptionPane.WARNING_MESSAGE);
        else{

            LabTestWorkRequest request = new LabTestWorkRequest();
            request.setPatientName(txtPatientName.getText());
            request.setMessage(areaTests.getText());
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setRequestType("Lab Test Request");

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof LabOrganization){
                    org = organization;
                    break;
                }
            }
            if (org!=null){
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }

            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTests;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JLabel testsLabel;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
